Traceback (most recent call last):
  File "/home/runner/work/ostatslib/ostatslib/.venv/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/work/ostatslib/ostatslib/.venv/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/ostatslib/ostatslib/.venv/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/work/ostatslib/ostatslib/.venv/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/runner/work/ostatslib/ostatslib/.venv/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/work/ostatslib/ostatslib/.venv/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import random
import pmlb
from IPython.display import Markdown
from ostatslib.agents import PPOAgent

SAMPLE_FRACTION = 0.1
sample_size = int(len(pmlb.classification_dataset_names) * SAMPLE_FRACTION)
sampled_dataset_names = random.sample(pmlb.classification_dataset_names, sample_size)

AGENT_FILE = '../trained_ppo_model.zip'
agent = PPOAgent(AGENT_FILE)

Markdown(f'Sampled {sample_size} classification datasets: {", ".join(sampled_dataset_names)}.')
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mRuntimeError[0m                              Traceback (most recent call last)
Cell [0;32mIn[2], line 11[0m
[1;32m      8[0m sampled_dataset_names [38;5;241m=[39m random[38;5;241m.[39msample(pmlb[38;5;241m.[39mclassification_dataset_names, sample_size)
[1;32m     10[0m AGENT_FILE [38;5;241m=[39m [38;5;124m'[39m[38;5;124m../trained_ppo_model.zip[39m[38;5;124m'[39m
[0;32m---> 11[0m agent [38;5;241m=[39m [43mPPOAgent[49m[43m([49m[43mAGENT_FILE[49m[43m)[49m
[1;32m     13[0m Markdown([38;5;124mf[39m[38;5;124m'[39m[38;5;124mSampled [39m[38;5;132;01m{[39;00msample_size[38;5;132;01m}[39;00m[38;5;124m classification datasets: [39m[38;5;132;01m{[39;00m[38;5;124m"[39m[38;5;124m, [39m[38;5;124m"[39m[38;5;241m.[39mjoin(sampled_dataset_names)[38;5;132;01m}[39;00m[38;5;124m.[39m[38;5;124m'[39m)

File [0;32m~/work/ostatslib/ostatslib/ostatslib/agents/ppo_agent.py:38[0m, in [0;36mPPOAgent.__init__[0;34m(self, path, training_envs_count, environment_kwargs)[0m
[1;32m     33[0m [38;5;28;01mdef[39;00m [38;5;21m__init__[39m([38;5;28mself[39m,
[1;32m     34[0m              path: [38;5;28mstr[39m [38;5;241m|[39m [38;5;28;01mNone[39;00m [38;5;241m=[39m [38;5;28;01mNone[39;00m,
[1;32m     35[0m              training_envs_count: [38;5;28mint[39m [38;5;241m=[39m [38;5;241m8[39m,
[1;32m     36[0m              environment_kwargs: [38;5;28mdict[39m [38;5;241m|[39m [38;5;28;01mNone[39;00m [38;5;241m=[39m [38;5;28;01mNone[39;00m) [38;5;241m-[39m[38;5;241m>[39m [38;5;28;01mNone[39;00m:
[1;32m     37[0m     [38;5;28mself[39m[38;5;241m.[39m__environment_kwargs [38;5;241m=[39m environment_kwargs
[0;32m---> 38[0m     [38;5;28mself[39m[38;5;241m.[39m__model [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m__init__model[49m[43m([49m[43mpath[49m[43m,[49m[43m [49m[43mtraining_envs_count[49m[43m)[49m

File [0;32m~/work/ostatslib/ostatslib/ostatslib/agents/ppo_agent.py:70[0m, in [0;36mPPOAgent.__init__model[0;34m(self, path, training_envs_count)[0m
[1;32m     63[0m [38;5;28;01mif[39;00m path [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m     64[0m     [38;5;28;01mreturn[39;00m PPO(POLICY,
[1;32m     65[0m                environments,
[1;32m     66[0m                verbose[38;5;241m=[39m[38;5;241m1[39m,
[1;32m     67[0m                n_steps[38;5;241m=[39m[38;5;241m1024[39m,
[1;32m     68[0m                policy_kwargs[38;5;241m=[39mPOLICY_KWARGS)
[0;32m---> 70[0m [38;5;28;01mreturn[39;00m [43mPPO[49m[38;5;241;43m.[39;49m[43mload[49m[43m([49m[43mpath[49m[43m,[49m
[1;32m     71[0m [43m                [49m[43menvironments[49m[43m,[49m
[1;32m     72[0m [43m                [49m[43mcustom_objects[49m[38;5;241;43m=[39;49m[43m{[49m
[1;32m     73[0m [43m                    [49m[38;5;124;43m'[39;49m[38;5;124;43mobservation_space[39;49m[38;5;124;43m'[39;49m[43m:[49m[43m [49m[43menvironments[49m[38;5;241;43m.[39;49m[43mobservation_space[49m[43m,[49m
[1;32m     74[0m [43m                    [49m[38;5;124;43m'[39;49m[38;5;124;43maction_space[39;49m[38;5;124;43m'[39;49m[43m:[49m[43m [49m[43menvironments[49m[38;5;241;43m.[39;49m[43maction_space[49m
[1;32m     75[0m [43m                [49m[43m}[49m[43m)[49m

File [0;32m~/work/ostatslib/ostatslib/.venv/lib/python3.11/site-packages/stable_baselines3/common/base_class.py:761[0m, in [0;36mBaseAlgorithm.load[0;34m(cls, path, env, device, custom_objects, print_system_info, force_reset, **kwargs)[0m
[1;32m    752[0m         warnings[38;5;241m.[39mwarn(
[1;32m    753[0m             [38;5;124m"[39m[38;5;124mYou are probably loading a model saved with SB3 < 1.7.0, [39m[38;5;124m"[39m
[1;32m    754[0m             [38;5;124m"[39m[38;5;124mwe deactivated exact_match so you can save the model [39m[38;5;124m"[39m
[0;32m   (...)[0m
[1;32m    758[0m             [38;5;124m"[39m[38;5;124mNote: the model should still work fine, this only a warning.[39m[38;5;124m"[39m
[1;32m    759[0m         )
[1;32m    760[0m     [38;5;28;01melse[39;00m:
[0;32m--> 761[0m         [38;5;28;01mraise[39;00m e
[1;32m    762[0m [38;5;66;03m# put other pytorch variables back in place[39;00m
[1;32m    763[0m [38;5;28;01mif[39;00m pytorch_variables [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:

File [0;32m~/work/ostatslib/ostatslib/.venv/lib/python3.11/site-packages/stable_baselines3/common/base_class.py:745[0m, in [0;36mBaseAlgorithm.load[0;34m(cls, path, env, device, custom_objects, print_system_info, force_reset, **kwargs)[0m
[1;32m    741[0m model[38;5;241m.[39m_setup_model()
[1;32m    743[0m [38;5;28;01mtry[39;00m:
[1;32m    744[0m     [38;5;66;03m# put state_dicts back in place[39;00m
[0;32m--> 745[0m     [43mmodel[49m[38;5;241;43m.[39;49m[43mset_parameters[49m[43m([49m[43mparams[49m[43m,[49m[43m [49m[43mexact_match[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m,[49m[43m [49m[43mdevice[49m[38;5;241;43m=[39;49m[43mdevice[49m[43m)[49m
[1;32m    746[0m [38;5;28;01mexcept[39;00m [38;5;167;01mRuntimeError[39;00m [38;5;28;01mas[39;00m e:
[1;32m    747[0m     [38;5;66;03m# Patch to load Policy saved using SB3 < 1.7.0[39;00m
[1;32m    748[0m     [38;5;66;03m# the error is probably due to old policy being loaded[39;00m
[1;32m    749[0m     [38;5;66;03m# See https://github.com/DLR-RM/stable-baselines3/issues/1233[39;00m
[1;32m    750[0m     [38;5;28;01mif[39;00m [38;5;124m"[39m[38;5;124mpi_features_extractor[39m[38;5;124m"[39m [38;5;129;01min[39;00m [38;5;28mstr[39m(e) [38;5;129;01mand[39;00m [38;5;124m"[39m[38;5;124mMissing key(s) in state_dict[39m[38;5;124m"[39m [38;5;129;01min[39;00m [38;5;28mstr[39m(e):

File [0;32m~/work/ostatslib/ostatslib/.venv/lib/python3.11/site-packages/stable_baselines3/common/base_class.py:631[0m, in [0;36mBaseAlgorithm.set_parameters[0;34m(self, load_path_or_dict, exact_match, device)[0m
[1;32m    628[0m         attr[38;5;241m.[39mload_state_dict(params[name])  [38;5;66;03m# type: ignore[arg-type][39;00m
[1;32m    629[0m     [38;5;28;01melse[39;00m:
[1;32m    630[0m         [38;5;66;03m# Assume attr is th.nn.Module[39;00m
[0;32m--> 631[0m         [43mattr[49m[38;5;241;43m.[39;49m[43mload_state_dict[49m[43m([49m[43mparams[49m[43m[[49m[43mname[49m[43m][49m[43m,[49m[43m [49m[43mstrict[49m[38;5;241;43m=[39;49m[43mexact_match[49m[43m)[49m
[1;32m    632[0m     updated_objects[38;5;241m.[39madd(name)
[1;32m    634[0m [38;5;28;01mif[39;00m exact_match [38;5;129;01mand[39;00m updated_objects [38;5;241m!=[39m objects_needing_update:

File [0;32m~/work/ostatslib/ostatslib/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py:2041[0m, in [0;36mModule.load_state_dict[0;34m(self, state_dict, strict)[0m
[1;32m   2036[0m         error_msgs[38;5;241m.[39minsert(
[1;32m   2037[0m             [38;5;241m0[39m, [38;5;124m'[39m[38;5;124mMissing key(s) in state_dict: [39m[38;5;132;01m{}[39;00m[38;5;124m. [39m[38;5;124m'[39m[38;5;241m.[39mformat(
[1;32m   2038[0m                 [38;5;124m'[39m[38;5;124m, [39m[38;5;124m'[39m[38;5;241m.[39mjoin([38;5;124m'[39m[38;5;124m"[39m[38;5;132;01m{}[39;00m[38;5;124m"[39m[38;5;124m'[39m[38;5;241m.[39mformat(k) [38;5;28;01mfor[39;00m k [38;5;129;01min[39;00m missing_keys)))
[1;32m   2040[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(error_msgs) [38;5;241m>[39m [38;5;241m0[39m:
[0;32m-> 2041[0m     [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m([38;5;124m'[39m[38;5;124mError(s) in loading state_dict for [39m[38;5;132;01m{}[39;00m[38;5;124m:[39m[38;5;130;01m\n[39;00m[38;5;130;01m\t[39;00m[38;5;132;01m{}[39;00m[38;5;124m'[39m[38;5;241m.[39mformat(
[1;32m   2042[0m                        [38;5;28mself[39m[38;5;241m.[39m[38;5;18m__class__[39m[38;5;241m.[39m[38;5;18m__name__[39m, [38;5;124m"[39m[38;5;130;01m\n[39;00m[38;5;130;01m\t[39;00m[38;5;124m"[39m[38;5;241m.[39mjoin(error_msgs)))
[1;32m   2043[0m [38;5;28;01mreturn[39;00m _IncompatibleKeys(missing_keys, unexpected_keys)

[0;31mRuntimeError[0m: Error(s) in loading state_dict for MultiInputActorCriticPolicy:
	size mismatch for mlp_extractor.policy_net.0.weight: copying a param with shape torch.Size([128, 43]) from checkpoint, the shape in current model is torch.Size([128, 64]).
	size mismatch for mlp_extractor.value_net.0.weight: copying a param with shape torch.Size([64, 43]) from checkpoint, the shape in current model is torch.Size([64, 64]).

